const STATUS = {
  NEW: 0,
  PENDING_APPROVAL: 1,
  APPROVED: 2,
  REJECTED: 3,
  COMPLETED: 4,
  CLOSED: 5,
};

const ACTIVE = {
  ACTIVE: 0,
  INACTIVE: 1,
};

const ROLES = {
  ADMIN: "admin",
  MANAGER: "manager",
  REVIEWER: "reviewer",
  USER: "user",
  VIEWER: "viewer",
};

const ERROR_CODES = {
  ERR_INVALID_CREDENTIALS: "ERR_INVALID_CREDENTIALS",
  ERR_USER_NOT_FOUND: "ERR_USER_NOT_FOUND",
  ERR_USER_INACTIVE: "ERR_USER_INACTIVE",
  ERR_UNAUTHORIZED: "ERR_UNAUTHORIZED",
  ERR_FORBIDDEN: "ERR_FORBIDDEN",
  ERR_TOKEN_EXPIRED: "ERR_TOKEN_EXPIRED",
  ERR_INVALID_TOKEN: "ERR_INVALID_TOKEN",
  ERR_NOT_FOUND: "ERR_NOT_FOUND",
  ERR_VALIDATION: "ERR_VALIDATION",
  ERR_VALIDATION_ERROR: "ERR_VALIDATION_ERROR",
  ERR_DUPLICATE_ENTRY: "ERR_DUPLICATE_ENTRY",
  ERR_DATABASE: "ERR_DATABASE",
  ERR_DATABASE_ERROR: "ERR_DATABASE_ERROR",
  ERR_INTERNAL_SERVER: "ERR_INTERNAL_SERVER",
  ERR_BAD_REQUEST: "ERR_BAD_REQUEST",
  ERR_DUPLICATE_ITEM_CODE: "ERR_DUPLICATE_ITEM_CODE",
  ERR_INVALID_CATEGORY: "ERR_INVALID_CATEGORY",
  ERR_INVALID_ITEM_TYPE: "ERR_INVALID_ITEM_TYPE",
  ERR_INVALID_UOM: "ERR_INVALID_UOM",
};

module.exports = {
  STATUS,
  ACTIVE,
  ROLES,
  ERROR_CODES,
};
